# Generated by Django 2.2.6 on 2019-10-08 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('base', models.CharField(choices=[('VANILLA', 'Vanilla'), ('CHOCOLATE', 'Chocolate')], default='VANILLA', max_length=100)),
                ('available', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], default='WEEKLY', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('date_churned', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date churned')),
            ],
        ),
    ]
